website/webapp/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView, 
    PostUpdateView, 
    PostDeleteView, 
    UserPostListView,
)
from .import views

app_name = 'webapp'
urlpatterns = [
    path("", PostListView.as_view(), name="home"),
    path("user/<str:username>", UserPostListView.as_view(), name="user-posts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>/update", PostUpdateView.as_view(), name="post-update"),
    path('post/new/', PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("about/", views.About, name="about"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.Register, name="register"),
    path('profile/', user_views.Profile, name="profile"),
    path('profile/update', user_views.ProfileUpdate, name="profile-update"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(template_name='users/passwordreset.html'), 
    name="password_reset"),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(template_name='users/passwordresetdone.html'), 
    name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(template_name='users/passwordresetconfirm.html'), 
    name="password_reset_confirm"),
    path('password-reset-complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name='users/passwordresetcomplete.html'), 
    name="password_reset_complete"),
    path('', include('webapp.urls')),   
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

website/webapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=300)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("webapp:post-detail", kwargs={'pk': self.pk})

website/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image',]

website/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required

def Register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Your Account has been created, {username}! You are now able to login.")
            return redirect('/login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'title': 'Register'})

def Profile(request):
    u_form = UserUpdateForm(request.POST, instance=request.user)
    p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'users/profile.html', context)

@login_required
def ProfileUpdate(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated")
            return redirect("/profile")

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }

    return render(request, 'users/profileupdate.html', context)

website/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib import messages


class PostListView(ListView):
    model = Post
    template_name = 'webapp/home.html'
    context_object_name = 'posts'
    ordering = ['-date']
    paginate_by = 5

class UserPostListView(ListView):
    model = Post
    template_name = 'webapp/userposts.html'
    context_object_name = 'posts'
    ordering = ['-date']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date')

class PostDetailView(DetailView):
    model = Post
    template_name = 'webapp/detail.html'

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'webapp/postcreate.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def message(self, request):
        messages.success(request, f"Your Post has been created")
        return redirect('/')

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'webapp/postupdate.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'webapp/postdelete.html'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def About(request):
    return render(request, "webapp/about.html", {'title': 'About'})

website/users/templates/users/login.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Login</button>
            </div>
            <div class="form-group">
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot your password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                You don't have an Account yet? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

website/users/templates/users/logout.html
{% extends 'webapp/base.html' %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

website/users/templates/users/passwordreset.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group d-flex">
                <button class="btn btn-outline-primary mr-auto" type="submit">Request Reset</button>
                <a class="btn btn-outline-danger" href="{% url 'login' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

website/users/templates/users/passwordresetcomplete.html
{% extends 'webapp/base.html' %}
{% block content %}
    <div class="alert-info">
        Your password has been updated.
    </div>
    <a href="{% url 'login' %}">Log In Here</a>
{% endblock content %}

website/users/templates/users/passwordresetconfirm.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group d-flex">
                <button class="btn btn-outline-primary mr-auto" type="submit">Reset Password</button>
                <a class="btn btn-outline-danger" href="{% url 'password_reset' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

website/users/templates/users/passwordresetdone.html
{% extends 'webapp/base.html' %}
{% block content %}
    <div class="alert-info">
        An E-mail has been sent with instructions to reset your password
    </div>
{% endblock content %}

website/users/templates/users/profile.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                    <h5 style="color: rgb(63, 63, 209)" class="mr-4">Username*</h5>
                    <h6>{{ user.username }}</h6>
                    <br>
                    <h5 style="color: rgb(63, 63, 209)" class="mr-4">Email*</h5>
                    <h6>{{ user.email }}</h6>
                    <br>
                    <h5 style="color: rgb(63, 63, 209)">Image*</h5>
                    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            </fieldset>
            {% if request.user.email == user.email %}
            <div class="form-group">
                <a class="btn btn-outline-primary" href="{% url 'profile-update' %}">Edit Profile</a>
            </div>
            {% endif %}
        </form>
    </div>
{% endblock content %}

website/users/templates/users/profileupdate.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Done</button>
            </div>
        </form>
    </div>
{% endblock content %}

website/users/templates/users/register.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up Free</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an Account? <a class="ml-2" href="{% url 'login' %}">Log In</a>
            </small>
        </div>
    </div>
{% endblock content %}

website/webapp/templates/webapp/about.html
{% extends "webapp/base.html" %}
{% block content %}
<img src="/webapp/static/webapp/images/Autumn.jpg/" alt="">
    <h3>This is a very special blog; it started in April 2020 and has become a ... vleivbslfl obleypfb bvb lyg liub lglqblbl ig;ubl
        lvihl ldj hluh;jh;jgef ;jl lih afhc; jbl ksbldk b fl jbldh bljv bl lefbl bld blef bl a;lna'/l q.ab  l b.lvfs.a;
        ickjhsdvkjeknvf, kjellvf lslfv bls, d,fk.
    </h3>
{% endblock content %}

website/webapp/templates/webapp/base.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'webapp/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title}}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'webapp:home' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'webapp:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'webapp:about' %}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'webapp:post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>This is a blog.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
<script src="/webapp/static/webapp/main.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

website/webapp/templates/webapp/detail.html
{% extends "webapp/base.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'webapp:user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
            {% if object.author == user %}
                <div class="d-flex">
                    <a class="btn btn-primary mt-1 mb-1 mr-auto" href="{% url 'webapp:post-update' object.id %}">Update</a>
                    <a class="btn btn-danger mt-1 mb-1" href="{% url 'webapp:post-delete' object.id %}">Delete</a>
                </div>
            {% endif %}
        </div>
    </article>
{% endblock content %}

website/webapp/templates/webapp/home.html
{% extends "webapp/base.html" %}
{% block content %}
    <div>
        {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-dark text-white mb-4 active" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
                <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
    </div>

    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'webapp:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="/post/{{ post.id }}/">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}
    

website/webapp/templates/webapp/postcreate.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

website/webapp/templates/webapp/postdelete.html
{% extends 'webapp/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete your Post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group d-flex">
                <button class="btn btn-outline-primary mr-auto" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-danger" href="{% url 'webapp:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

website/webapp/templates/webapp/postupdate.html
{% extends 'webapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group d-flex">
                <button class="btn btn-outline-primary mr-auto" type="submit">Update and Post</button>
                <a class="btn btn-outline-secondary" href="{% url 'webapp:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

website/webapp/templates/webapp/userposts.html
{% extends "webapp/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    <div>
        {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-dark mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-dark text-white active mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
                <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
    </div>

    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'webapp:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="/post/{{ post.id }}/">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}